# 1. Configuración de Base de Datos (Ya la tienes con el .env y el Main)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Usamos 'update' para no borrar lo que creaste a mano, 
# pero 'generate-ddl' para que cree las tablas nuevas que faltan (como Wallet)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# Dialecto actualizado para Spring Boot 3.x y MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Mostrar SQL en consola para depurar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Forzar inicialización
spring.sql.init.mode=always

# 1. Apagar el Banner gigante de SPRING
spring.main.banner-mode=off

# 2. Apagar los logs de arranque ("Starting AppBot...", "Tomcat started...")
spring.main.log-startup-info=false
